# This workflow will install Python dependencies, run tests with pytest and lint with a single version of Python

name: Flask application testing

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'README.md'
      - '.gitignore'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - 'README.md'
      - '.gitignore'

  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Testing step
      run: |
        echo "The following is the result of testing our flask application ::  "
        pytest